### ISSUE TITLE
Sox depends on libltdl

### ISSUE THREAD

**Issue by 183amir** [conda-forge/sox-feedstock#5]
While trying to use sox here: https://github.com/conda-forge/bob.io.audio-feedstock/pull/4, I saw this error:
```python
import: 'bob.io.audio'

Traceback (most recent call last):

  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 31, in <module>

    import bob.io.audio

  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/bob/io/audio/__init__.py", line 4, in <module>

    from ._library import *

ImportError: dlopen(/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/bob/io/audio/_library.so, 2): Library not loaded: /usr/local/lib/libltdl.7.dylib

  Referenced from: /Users/travis/miniconda3/envs/_test/lib/libsox.3.dylib

  Reason: image not found
```

**Comment by 183amir** [comment]
This was fixed by deleting old sox builds.
